/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop.wifihertz;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Łukasz
 */
public class ImageJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form ImageJPanel
     */
    public ImageJPanel()
    {
        initComponents();
    }
    private Image image;

    public void scaleImage(double scale)
    {
        if (image != null)
        {
            int newWidth = (int) ((double) image.getWidth(this) * scale);
            int newHeight = (int) ((double) image.getHeight(this) * scale);

            image = image.getScaledInstance(newWidth, newHeight, 0);

            setPanelSize(newWidth, newHeight);

            repaint();
        }
    }

    private void setPanelSize(int width, int height)
    {
        this.setPreferredSize(new Dimension(width, height));
        this.setSize(width, height);
        this.setMaximumSize(new Dimension(width, height));

    }

    @Override
    public void paint(Graphics x)
    {
        Graphics2D g = (Graphics2D) x;

        super.paint(g);
       
            try
            {
                image = ImageIO.read(new File(ManageJPanel.sourceImagePath));
            }
            catch (IOException ex)
            {
                Logger.getLogger(ImageJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        

        //plansza = imageTemp1.getImage();
        g.drawImage(image, 0, 0, this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
